import Link from '@/components/Link';
import { features } from '@/content';
import { ProductMockup } from '@/components/ProductMockup';
import { CTA } from '@/components/CTA';

const flow=['Lead','Qualification','Quotation','Booking','Payment','Ops handover','Travel','Follow-up'];
const roles=[['Sales','Capture · Follow up · Quote · Book · Collect'],['Operations','Receive handover · Assign · Confirm · Execute'],['Sales manager','Approve · Oversee pipeline · Improve conversion'],['Tenant admin','Configure · Manage users · Report · Assure quality']];

export default function Home(){return <>
  <section className="hero"><div className="route-line"/><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">The operating system for tour businesses</p><h1>Run your tour business from <em>enquiry to execution.</em></h1><p className="lead">TripHulu connects sales, quotations, bookings, payments, customer communication and ground operations in one workflow built for tour operators.</p><div className="actions"><Link className="button" href="/contact">Book a demo <span>↗</span></Link><Link className="text-link" href="/features">Explore features →</Link></div><div className="trust"><span>Built for</span><b>Tour operators</b><b>DMCs</b><b>Travel agencies</b></div></div><div className="hero-visual"><div className="stamp">Lead<br/><b>to</b><br/>Journey</div><ProductMockup/></div></div></section>
  <section className="flow-section"><div className="shell"><div className="section-heading split"><div><p className="eyebrow">A connected lifecycle</p><h2>Every stage knows what happened before it.</h2></div><p>Reduce manual re-entry, spreadsheet sprawl and handover gaps with one shared journey record.</p></div><div className="flow">{flow.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div>)}</div></div></section>
  <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">One platform, eight connected modules</p><h2>Move the business forward—not the same data between tools.</h2></div><div className="feature-grid">{features.slice(0,8).map((f,i)=><Link className="feature-card" href={`/features/${f.slug}`} key={f.slug}><span className="card-index">0{i+1}</span><p className="kicker">{f.eyebrow}</p><h3>{f.title}</h3><p>{f.outcome}</p><b>Explore <span>↗</span></b></Link>)}</div></div></section>
  <section className="dark-section"><div className="shell two-col"><div><p className="eyebrow warm">Sales → Operations</p><h2>Your team closes the booking. Operations receives the context.</h2><p className="lead small-lead">No separate handover spreadsheet. No reconstructing decisions from chat. A confirmed booking moves into a visible checklist for stays, transport, reconfirmation and travel readiness.</p><ul className="check-list"><li>Automatic Ops handover</li><li>Hotel, driver and vehicle assignments</li><li>Confirmation and reconfirmation states</li><li>Clear ready-to-travel status</li></ul><Link className="button cream" href="/features/operations">Explore Operations →</Link></div><ProductMockup mode="ops"/></div></section>
  <section className="section roles"><div className="shell"><div className="section-heading split"><div><p className="eyebrow">Built around ownership</p><h2>A clearer day for every role.</h2></div><p>Each team sees the work, decisions and handovers relevant to them—without losing the wider trip context.</p></div><div className="role-grid">{roles.map((r,i)=><div key={r[0]}><span>0{i+1}</span><h3>{r[0]}</h3><p>{r[1]}</p></div>)}</div></div></section>
  <section className="problem-section"><div className="shell problem-grid"><div><p className="eyebrow">Why TripHulu</p><h2>Tour operations are too important to run between disconnected tabs.</h2></div><div className="compare"><div><p className="kicker">Without TripHulu</p><ul><li>Spreadsheets multiply</li><li>Customer messages scatter</li><li>Quotes are re-entered as bookings</li><li>Payment state lives elsewhere</li><li>Handover context gets lost</li></ul></div><div className="answer"><p className="kicker">With TripHulu</p><ul><li>One connected workflow</li><li>Standard communication</li><li>Structured handovers</li><li>Auditable payment state</li><li>Visible trip readiness</li></ul></div></div></div></section>
  <CTA/>
</>}
