export type Feature = { slug: string; eyebrow: string; title: string; summary: string; outcome: string; points: string[]; note?: string; flow?: string[] };

export const features: Feature[] = [
  { slug:'sales', eyebrow:'Sell', title:'Sales & lead management', summary:'Turn enquiries into an accountable sales pipeline.', outcome:'Capture the details that matter, keep ownership visible, and move qualified travellers into a quotation without losing context.', points:['Lead capture and source tracking','Salesperson assignment','Hot, warm, cold and lost qualification','Follow-ups, search and filters','Package and travel preferences','Lead-to-quotation transition'] },
  { slug:'quotations', eyebrow:'Sell', title:'Quotation management', summary:'Build a commercial offer without rebuilding the trip every time.', outcome:'Keep the enquiry, trip structure, pricing and approval trail together as a quote moves toward confirmation.', points:['Structured package, pax and date details','Editable quotations','Discount and approval workflows','Quote locking','Customer-ready sharing','Book Now transition'], flow:['Enquiry','Draft quote','Approval','Locked offer','Book now'] },
  { slug:'bookings', eyebrow:'Book', title:'Booking pipeline', summary:'See what is booked, paid, pending and operationally ready.', outcome:'Give Sales and Operations a shared, current view of each confirmed journey and the actions it needs next.', points:['Customer booking lifecycle','Traveller breakdown','Pickup and drop details','Payment and Ops status','Salesperson ownership','Search, filters and quick actions'] },
  { slug:'payments', eyebrow:'Book', title:'Payments', summary:'Keep collections connected to the booking they belong to.', outcome:'Record advances, part-payments and balances in a clear ledger, with verification workflows determined by each tenant’s setup.', points:['Advance and part payments','Balance collection','Online payment links','Cash recording','Payment ledger and balance due','Provider-backed reconciliation'], note:'Payment providers and configuration depend on tenant setup.' },
  { slug:'operations', eyebrow:'Operate', title:'Operations', summary:'Close the booking. Hand over the context automatically.', outcome:'Turn a confirmed sale into an actionable operating plan with clear ownership, checkpoints and readiness status.', points:['Automatic Ops handover','Hotel and stay assignments','Driver and vehicle assignments','Pending and confirmed states','Handover checklist','Reconfirmation and ready-to-travel'], flow:['Booking confirmed','Ops handover','Stay assignment','Transport','Confirmation','Reconfirmation','Ready to travel'] },
  { slug:'travel-intelligence', eyebrow:'Plan', title:'Travel intelligence', summary:'Plan with structured travel data before converting the recommendation into a booking.', outcome:'Help Sales evaluate routes, stays, vehicles and trip structure in a consistent planning workflow.', points:['Structured route planning','Stay options','Vehicle considerations','Trip structure review','Recommendation-to-booking transition','Human-led planning decisions'], note:'No unsupported generative-AI claims: recommendations remain structured and reviewable.' },
  { slug:'communications', eyebrow:'Communicate', title:'Customer communications', summary:'Give every customer a timely, consistent message at each trip milestone.', outcome:'Standardize WhatsApp-ready communication while keeping Sales and Operations aligned on what has been shared.', points:['First response and detail request','Itinerary and booking readiness','Payment instructions and receipt','Booking confirmation','Pre-travel point of contact','Balance reminder and feedback'], flow:['C1 Request details','C7 Ready to book','C9 Payment received','C10 Booking confirmation','C12 Pre-travel POC','C13 Balance reminder','C14 Feedback'] },
  { slug:'analytics', eyebrow:'Manage', title:'Analytics & dashboard', summary:'Turn daily activity into an operational view.', outcome:'Bring sales, collections and trip-readiness signals together so managers can focus attention where it matters.', points:['Lead pipeline','Conversion visibility','Revenue overview','Pending payments','Ops workload','Daily and weekly travel views'] },
  { slug:'quality', eyebrow:'Assure', title:'Quality & release assurance', summary:'Know your workflow is healthy before your team discovers it.', outcome:'Authorized tenant and admin users can combine automated regression checks with manual release assurance across critical workflows.', points:['Authenticated tenant test packs','API and browser validation','Smoke and customer UAT suites','P0/P1 regression coverage','Private screenshots and evidence','Sanitized release reports'], flow:['Select tenant','Run smoke','Run customer UAT','Review evidence','Release verdict'], note:'Automated regression supports—not replaces—manual QA.' },
];

export const nav = [
  { href:'/features', label:'Features' }, { href:'/pricing', label:'Pricing' }, { href:'/about', label:'About' }, { href:'/security', label:'Security' }
];
